### ISSUE TITLE
[BUG] 无法在 1.18 上运行

### ISSUE THREAD

**Issue by MiniDay** [mrjesen/ImBlockerFabric#39]
**Describe the bug**
安装mod后启动游戏时会发生报错

**Client Software**
HMCL (MC: 1.18)

**mods**
 见下方详细日志

**To Reproduce**
1. 安装 fabric-loader 0.12.8
2. 安装 imblocker 1.0.16
3. 启动游戏

**Expected behavior**
游戏能够正常启动

**Screenshots**
见下方日志

**Environment (Please complete the following information):**
 - OS: Windows 10 21H2
 - REI: 7.0.341

**Additional context**
```
net.fabricmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: net/minecraft/class_1279
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:601)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_1279
	at net.minecraft.client.main.Main.main(Main.java:206)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599)
	... 2 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_1279
	... 8 more
```

完整的运行日志：https://gist.github.com/MiniDay/b93202bc504ec2eafa0e29a992efd820

（测试后发现即使仅安装 `imblockerfabric-1.0.16.jar` 也同样会崩溃，错误原因仍是`java.lang.ClassNotFoundException: net.minecraft.class_1279`）

**Comment by ColdTearsYY** [comment]
我也有同样的错误

**Comment by mrjesen** [comment]
ok 有时间修

**Comment by MiniDay** [comment]
> @plusls 😎看完log4j了吗，有时间看看能修吗 我最近没啥时间

这个问题昨晚我已经联系fabric开发团队修复了，更新fabric loader就行。

**Comment by mrjesen** [comment]
> 

意思是现在已经可以正常是使用了是吗

**Comment by MiniDay** [comment]
> > 
> 
> 意思是现在已经可以正常是使用了是吗

是的，更新loader到最新版本就行。

**Comment by xiaoyang5202480** [comment]
我也是，麻了

**Comment by plusls** [comment]
> @plusls 😎看完log4j了吗，有时间看看能修吗 我最近没啥时间

太为难我了 我不会web的
