### ISSUE TITLE
[BUG] 无法在 1.18.1/1.18 上运行

### ISSUE THREAD

**Issue by Skimige** [mrjesen/ImBlockerFabric#41]
**Describe the bug**
启用此 Mod 会导致游戏启动崩溃。

**Client Software**
Plain Craft Launcher 2 (Snapshot 2.2.7 (243.0)) w/ Minecraft 1.18+Fabric 0.12.12+FabricAPI 0.43.1
Minecraft Launcher 1.0.104.0 w/ Minecraft 1.18.1+Fabric 0.12.12+FabricAPI 0.44.0

**mods**
 - fabric-api

**To Reproduce**
*Steps to reproduce the behavior:*
1. 启动游戏

**Expected behavior**
游戏正常启动

**Screenshots**
*If applicable, add screenshots to help explain your problem.*
Not applicable.

**Environment (Please complete the following information):**
 - OS: Windows 10 21H2
 - JRE: Oracle JDK 17.0.1 (PCL2) / OpenJDK 17.0.1 (MC Launcher)

**Additional context**
*Add any other context about the problem here.*

Picked lines:
```log
[17:03:18] [main/WARN]: Error loading class: com/replaymod/lib/de/johni0702/minecraft/gui/element/AbstractGuiTextField (java.lang.ClassNotFoundException: com/replaymod/lib/de/johni0702/minecraft/gui/element/AbstractGuiTextField)
[17:03:18] [main/WARN]: Error loading class: io/github/cottonmc/cotton/gui/widget/WWidget (java.lang.ClassNotFoundException: io/github/cottonmc/cotton/gui/widget/WWidget)
[17:03:18] [main/WARN]: Error loading class: io/github/cottonmc/cotton/gui/widget/WTextField (java.lang.ClassNotFoundException: io/github/cottonmc/cotton/gui/widget/WTextField)

...

[17:03:26] [Render thread/WARN]: Error loading class: net/minecraft/class_1279 (java.lang.ClassNotFoundException: net/minecraft/class_1279)
[17:03:26] [Render thread/INFO]: Failed to find module info for D:\PlainCraftLauncher2\.minecraft\versions\1.18.1-Fabric 0.12.12\1.18.1-Fabric 0.12.12-natives\lwjgl.dll
com.sun.jna.platform.win32.Win32Exception: 找不到映像文件中指定的资源类型。
	at net.minecraft.class_6498.method_37964(class_6498.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37961(class_6498.java:48) ~[client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37968(class_6498.java:132) ~[client-intermediary.jar:?]
	at net.minecraft.class_129.method_577(class_129.java:84) [client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37966(class_6498.java:131) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:207) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]

...

[17:03:26] [Render thread/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: net/minecraft/class_1279
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:610) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_1279
	at net.minecraft.client.main.Main.main(Main.java:208) ~[1.18.1-Fabric%200.12.12.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
	... 2 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_1279
	at net.minecraft.client.main.Main.main(Main.java:208) ~[1.18.1-Fabric%200.12.12.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
	... 2 more

...
```

Full logs:
- Minecraft Launcher 1.18.1: [2021-12-19-MCL.log](https://github.com/mrjesen/ImBlockerFabric/files/7740545/2021-12-19-MCL.log)
- PCL2 1.18: [2021-12-19-PCL2.log](https://github.com/mrjesen/ImBlockerFabric/files/7740547/2021-12-19-PCL2.log)

**Comment by Skimige** [comment]
Duplicate #39 , 但为什么说修了其实还是炸呢（
Minecraft Launcher 使用 fabric-installer-0.10.2.exe 安装

**Comment by mrjesen** [comment]
在mcbbs上有人提了log了，目测是缺dll

**Comment by mrjesen** [comment]
试一下这个版本呢
[imblockerfabric-1.0.17.zip](https://github.com/mrjesen/ImBlockerFabric/files/7740621/imblockerfabric-1.0.17.zip)

**Comment by mrjesen** [comment]
或者在D:\PlainCraftLauncher2\.minecraft\versions\1.18.1-Fabric 0.12.12\1.18.1-Fabric 0.12.12-natives\文件夹放入这个：
[lwjgl.zip](https://github.com/mrjesen/ImBlockerFabric/files/7740627/lwjgl.zip) （记得解压）

**Comment by mrjesen** [comment]
对比一下：
![image](https://user-images.githubusercontent.com/29056691/146671683-9103848e-00d6-4905-a2e1-12f85ae767aa.png)

**Comment by Skimige** [comment]
plusis: use #40 

#40 Actions output 可以正常使用，没测上面给的 zip 是否就是它

并不缺少此 dll，您提供的 dll 和我本地的完全一致。

**Comment by mrjesen** [comment]
> plusis: use #40
> 
> #40 Actions output 可以正常使用，没测上面给的 zip 是否就是它
> 
> 并不缺少此 dll，您提供的 dll 和我本地的完全一致。

 好的，上面给的zip一个就是这个mod，另一个是错误日志里面提示的那个dll
