### ISSUE TITLE
[BUG] 1.0.18 is incompatible with 1.16.5

### ISSUE THREAD

**Issue by SolidBlock-cn** [mrjesen/ImBlockerFabric#49]
**Describe the bug**
Mixin transformation error in IMBlockerFabric 1.0.18, even it is declared to be compatible with 1.14.4-1.18.2.

**Client Software**
HMCL (MC: 1.16.5)

**mods**
Fabric API 0.42.0+1.16
IMBlockerFabric 1.0.18

**To Reproduce**
1. No steps needed.

**Expected behavior**
No error expected.

**Screenshots**

**Environment (Please complete the following information):**
 - OS: Windows 11
 - JRE: Java 16.0.2

**Additional context**
Crash report:
```
Description: Initializing game

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_498 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:418)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:322)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at jp.axer.colorutility.ColorUtility.onScreenCreated(ColorUtility.java:25)
	at jp.axer.colorutility.ColorUtility.lambda$onInitializeClient$0(ColorUtility.java:21)
	at net.fabricmc.fabric.api.client.screen.v1.ScreenEvents.lambda$static$2(ScreenEvents.java:104)
	at net.minecraft.class_437.handler$zpm000$afterInitScreen(class_437.java:2647)
	at net.minecraft.class_437.method_25423(class_437.java:326)
	at net.minecraft.class_442.method_25426(class_442.java:136)
	at net.minecraft.class_437.method_25423(class_437.java:325)
	at net.minecraft.class_310.method_1507(class_310.java:922)
	at net.minecraft.class_310.<init>(class_310.java:579)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:413)
	... 17 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [imblocker.mixins.json:MixinSignEditScreenLegacy from mod imblocker] from phase [DEFAULT] in config [imblocker.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 20 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on postTick could not find any targets matching 'tick' in net.minecraft.class_498. Using refmap imblockerfabric-refmap.json [PREINJECT Applicator Phase -> imblocker.mixins.json:MixinSignEditScreenLegacy from mod imblocker -> Prepare Injections ->  -> handler$bak002$postTick(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
	at Not Enough Crashes deobfuscated stack trace.(1.16.1+build.21)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308)
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46)
	at jdk.internal.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1330)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:413)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:322)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at jp.axer.colorutility.ColorUtility.onScreenCreated(ColorUtility.java:25)
	at jp.axer.colorutility.ColorUtility.lambda$onInitializeClient$0(ColorUtility.java:21)
	at net.fabricmc.fabric.api.client.screen.v1.ScreenEvents.lambda$static$2(ScreenEvents.java:104)
	at net.minecraft.client.gui.screen.Screen.handler$zpm000$afterInitScreen(Screen:2647)
	at net.minecraft.client.gui.screen.Screen.init(Screen:326)
	at net.minecraft.client.gui.screen.TitleScreen.init(TitleScreen:136)
	at net.minecraft.client.gui.screen.Screen.init(Screen:325)
	at net.minecraft.client.MinecraftClient.openScreen(MinecraftClient:922)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:579)
	at net.minecraft.client.main.Main.main(Main:177)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by mrjesen** [comment]
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [imblocker.mixins.json:MixinSignEditScreenLegacy from mod imblocker] from phase [DEFAULT] in config [imblocker.mixins.json] FAILED during APPLY

**Comment by plusls** [comment]
是这样的，莫名其妙就会某个字段被混淆

然后没空测每个版本就会翻车

**Comment by mrjesen** [comment]
> 是这样的，莫名其妙就会某个字段被混淆
> 
> 然后没空测每个版本就会翻车

我一会测一下所有版本吧

**Comment by mrjesen** [comment]
1.15.2失败，不过是BookEdit的问题，还是tick方法找不到。
